Repository sasaping/sasaping-system, pull requests merged in 2024-10, with the labels that each got.

#16 상품관련 모듈 추가 및 라우팅 설정
  service/gateway/server/src/main/resources/application-local.yml
  service/product/product_dto/.gitignore
  service/product/product_dto/build.gradle
  service/product/product_dto/src/main/java/com/sparta/product_dto/ProductDtoApplication.java
  service/product/product_dto/src/test/java/com/sparta/product_dto/ProductDtoApplicationTests.java
  service/product/server/.gitignore
  service/product/server/build.gradle
  service/product/server/src/main/java/com/sparta/product/ProductServerApplication.java
  service/product/server/src/main/resources/application-local.yml
  service/product/server/src/test/java/com/sparta/product/ProductServerApplicationTests.java
  settings.gradle
Labels: ⚙️ Setting

#18 Order, Notification 모듈 생성
  service/notification/server/.gitignore
  service/notification/server/build.gradle
  service/notification/server/src/main/java/com/sparta/notification/server/NotificationApplication.java
  service/notification/server/src/main/resources/application-local.yml
  service/notification/server/src/main/resources/application.yml
  service/notification/server/src/test/java/com/sparta/notification/server/NotificationApplicationTests.java
  service/order/server/.gitignore
  service/order/server/build.gradle
  service/order/server/src/main/java/com/sparta/order/server/OrderApplication.java
  service/order/server/src/main/resources/application-local.yml
  service/order/server/src/main/resources/application.yml
  service/order/server/src/test/java/com/sparta/order/server/OrderApplicationTests.java
  settings.gradle
Labels: ✨ Feature

#19 Auth 모듈 생성 및 Gateway 필요없는 폴더 삭제
  service/auth/server/.gitignore
  service/auth/server/build.gradle
  service/auth/server/src/main/java/com/sparta/auth/server/AuthApplication.java
  service/auth/server/src/main/resources/application-local.yml
  service/auth/server/src/main/resources/application.yml
  service/auth/server/src/test/java/com/sparta/auth/server/AuthApplicationTests.java
  service/gateway/server/gradle/wrapper/gradle-wrapper.jar
  service/gateway/server/gradle/wrapper/gradle-wrapper.properties
  settings.gradle
Labels: ⚙️ Setting

#27 주문 DTO 모듈 생성
  service/order/dto/.gitignore
  service/order/dto/build.gradle
  service/order/dto/src/main/java/com/sparta/order/dto/OrderDtoApplication.java
  service/order/dto/src/main/java/dto/OrderDto.java
  service/order/dto/src/main/java/dto/OrderProductDto.java
  service/order/dto/src/main/resources/application.properties
  service/order/dto/src/test/java/com/sparta/order/dto/OrderDtoApplicationTests.java
  settings.gradle
Labels: ✨ Feature

#26 회원가입 기능 추가
  common/domain/src/main/resources/application.properties
  service/user/dto/.gitignore
  service/user/dto/build.gradle
  service/user/dto/src/test/java/com/sparta/user/DtoApplicationTests.java
  service/user/server/build.gradle
  service/user/server/gradle/wrapper/gradle-wrapper.jar
  service/user/server/gradle/wrapper/gradle-wrapper.properties
  service/user/server/src/main/java/com/sparta/user/ServerApplication.java
  service/user/server/src/main/java/com/sparta/user/UserApplication.java
  service/user/server/src/main/java/com/sparta/user/application/service/UserService.java
  service/user/server/src/main/java/com/sparta/user/domain/model/User.java
  service/user/server/src/main/java/com/sparta/user/domain/model/vo/UserRole.java
  service/user/server/src/main/java/com/sparta/user/domain/repository/UserRepository.java
  service/user/server/src/main/java/com/sparta/user/exception/UserErrorCode.java
  service/user/server/src/main/java/com/sparta/user/exception/UserException.java
  service/user/server/src/main/java/com/sparta/user/infrastructure/repository/JpaUserRepository.java
  service/user/server/src/main/java/com/sparta/user/infrastructure/repository/UserRepositoryImpl.java
  service/user/server/src/main/java/com/sparta/user/presentation/controller/UserController.java
  service/user/server/src/main/java/com/sparta/user/presentation/request/UserRequest.java
  service/user/server/src/main/resources/application.yml
  service/user/server/src/test/java/com/sparta/user/ServerApplicationTests.java
  service/user/server/src/test/java/com/sparta/user/UserApplicationTests.java
  service/user/server/src/test/java/com/sparta/user/http/UserApiTest.http
  settings.gradle
Labels: ✨ Feature

#31 주문 DTO gradle wrapper 오류 문제 해결
  service/order/dto/build.gradle
  service/order/dto/gradle/wrapper/gradle-wrapper.jar
  service/order/dto/gradle/wrapper/gradle-wrapper.properties
  service/order/dto/src/main/resources/application.properties
Labels: 🐞 Bug

#33 로그인 기능 구현 시 필요한 user.dto 모듈 구성
  service/user/dto/.gitignore
  service/user/dto/build.gradle
  service/user/dto/gradle/wrapper/gradle-wrapper.jar
  service/user/dto/gradle/wrapper/gradle-wrapper.properties
  service/user/dto/src/main/java/com/sparta/user/dto/DtoApplication.java
  service/user/dto/src/main/java/com/sparta/user/dto/infrastructure/UserInternalDto.java
  settings.gradle
Labels: ⚙️ Setting

#37 사용자 이름으로 조회 기능 구현 및 user.dto 수정
  service/user/dto/src/main/java/com/sparta/user/dto/infrastructure/UserDto.java
  service/user/server/build.gradle
  service/user/server/src/main/java/com/sparta/user/application/service/UserService.java
  service/user/server/src/main/java/com/sparta/user/exception/UserErrorCode.java
  service/user/server/src/main/java/com/sparta/user/presentation/controller/UserInternalController.java
  service/user/server/src/test/java/com/sparta/user/UserApplicationTests.java
Labels: ✨ Feature, 🛠Fix

#34 상품 추가 API 구현
  docker-compose.yml
  service/product/product_server/.gitignore
  service/product/product_server/build.gradle
  service/product/product_server/src/main/java/com/sparta/product/ProductServerApplication.java
  service/product/product_server/src/main/java/com/sparta/product/application/ElasticSearchService.java
  service/product/product_server/src/main/java/com/sparta/product/application/ProductFacadeService.java
  service/product/product_server/src/main/java/com/sparta/product/application/ProductMapper.java
  service/product/product_server/src/main/java/com/sparta/product/application/ProductService.java
  service/product/product_server/src/main/java/com/sparta/product/domain/model/Product.java
  service/product/product_server/src/main/java/com/sparta/product/domain/repository/ElasticSearchRepository.java
  service/product/product_server/src/main/java/com/sparta/product/domain/repository/cassandra/ProductRepository.java
  service/product/product_server/src/main/java/com/sparta/product/infrastructure/configuration/RepositoryConfig.java
  service/product/product_server/src/main/java/com/sparta/product/infrastructure/elasticsearch/dto/ProductSearchDto.java
  service/product/product_server/src/main/java/com/sparta/product/presentation/controller/ProductController.java
  service/product/product_server/src/main/java/com/sparta/product/presentation/request/ProductCreateRequest.java
  service/product/product_server/src/main/java/com/sparta/product/presentation/response/ProductResponse.java
  service/product/product_server/src/main/resources/application-local.yml
  service/product/product_server/src/test/java/com/sparta/product/ProductServerApplicationTests.java
  settings.gradle
Labels: ✨ Feature

#46 슬랙 전송 api 생성
  service/slack/server/src/main/java/com/sparta/slack/SlackApplication.java
  service/slack/server/src/main/java/com/sparta/slack/application/dto/MessageRequest.java
  service/slack/server/src/main/java/com/sparta/slack/application/dto/MessageResponse.java
  service/slack/server/src/main/java/com/sparta/slack/application/service/MessageService.java
  service/slack/server/src/main/java/com/sparta/slack/domain/entity/Message.java
  service/slack/server/src/main/java/com/sparta/slack/domain/repository/MessageRepository.java
  service/slack/server/src/main/java/com/sparta/slack/exception/MessageErrorCode.java
  service/slack/server/src/main/java/com/sparta/slack/exception/MessageException.java
  service/slack/server/src/main/java/com/sparta/slack/exception/MessageExceptionHandler.java
  service/slack/server/src/main/java/com/sparta/slack/presentation/controller/MessageController.java
  service/slack/server/src/main/resources/application-local.yml
Labels: ✨ Feature

#43 장바구니 상품 개수 수정, 상품 삭제, 전체삭제 API 구현
  service/order/server/build.gradle
  service/order/server/docs/CartApiTest.http
  service/order/server/src/main/java/com/sparta/order/server/Cart/application/service/CartService.java
  service/order/server/src/main/java/com/sparta/order/server/Cart/domain/model/CartProduct.java
  service/order/server/src/main/java/com/sparta/order/server/Cart/domain/model/ProductInfo.java
  service/order/server/src/main/java/com/sparta/order/server/Cart/exception/CartErrorCode.java
  service/order/server/src/main/java/com/sparta/order/server/Cart/exception/CartException.java
  service/order/server/src/main/java/com/sparta/order/server/Cart/exception/CartExceptionHandler.java
  service/order/server/src/main/java/com/sparta/order/server/Cart/infrastructure/configuration/RedisConfig.java
  service/order/server/src/main/java/com/sparta/order/server/Cart/presentation/controller/CartController.java
  service/order/server/src/main/java/com/sparta/order/server/Cart/presentation/dto/CartDto.java
  service/order/server/src/main/resources/application-local.yml
Labels: ✨ Feature

#49 상품 수정/삭제/상태변경 API 구현
  service/product/product_server/src/main/java/com/sparta/product/application/ElasticSearchService.java
  service/product/product_server/src/main/java/com/sparta/product/application/ProductFacadeService.java
  service/product/product_server/src/main/java/com/sparta/product/application/ProductMapper.java
  service/product/product_server/src/main/java/com/sparta/product/application/ProductService.java
  service/product/product_server/src/main/java/com/sparta/product/domain/model/Product.java
  service/product/product_server/src/main/java/com/sparta/product/domain/repository/cassandra/ProductRepository.java
  service/product/product_server/src/main/java/com/sparta/product/infrastructure/elasticsearch/dto/ProductSearchDto.java
  service/product/product_server/src/main/java/com/sparta/product/presentation/controller/ProductController.java
  service/product/product_server/src/main/java/com/sparta/product/presentation/exception/ProductControllerAdvice.java
  service/product/product_server/src/main/java/com/sparta/product/presentation/exception/ProductErrorCode.java
  service/product/product_server/src/main/java/com/sparta/product/presentation/exception/ProductServerException.java
  service/product/product_server/src/main/java/com/sparta/product/presentation/request/ProductUpdateRequest.java
  service/product/product_server/src/main/java/com/sparta/product/presentation/response/ProductResponse.java
Labels: ✨ Feature

#48 로그인 기능 구현
  service/auth/server/build.gradle
  service/auth/server/src/main/java/com/sparta/auth/server/AuthApplication.java
  service/auth/server/src/main/java/com/sparta/auth/server/application/dto/AuthResponse.java
  service/auth/server/src/main/java/com/sparta/auth/server/application/dto/JwtClaim.java
  service/auth/server/src/main/java/com/sparta/auth/server/application/service/AuthService.java
  service/auth/server/src/main/java/com/sparta/auth/server/application/service/UserService.java
  service/auth/server/src/main/java/com/sparta/auth/server/exception/AuthControllerAdvice.java
  service/auth/server/src/main/java/com/sparta/auth/server/exception/AuthErrorCode.java
  service/auth/server/src/main/java/com/sparta/auth/server/exception/AuthException.java
  service/auth/server/src/main/java/com/sparta/auth/server/infrastructure/configuration/JwtConfig.java
  service/auth/server/src/main/java/com/sparta/auth/server/infrastructure/configuration/UserFeignConfig.java
  service/auth/server/src/main/java/com/sparta/auth/server/infrastructure/feign/UserClient.java
  service/auth/server/src/main/java/com/sparta/auth/server/infrastructure/feign/UserErrorDecoder.java
  service/auth/server/src/main/java/com/sparta/auth/server/infrastructure/properties/JwtProperties.java
  service/auth/server/src/main/java/com/sparta/auth/server/infrastructure/utils/JwtHandler.java
  service/auth/server/src/main/java/com/sparta/auth/server/presentation/controller/AuthController.java
  service/auth/server/src/main/java/com/sparta/auth/server/presentation/request/AuthRequest.java
  service/auth/server/src/test/java/com/sparta/auth/server/AuthApplicationTests.java
  service/auth/server/src/test/java/com/sparta/auth/server/http/AuthApiTest.http
Labels: ✨ Feature

#53 장바구니 트랜잭션 적용 및 만료기한 설정
  service/order/server/docs/CartApiTest.http
  service/order/server/src/main/java/com/sparta/order/server/Cart/application/service/CartService.java
  service/order/server/src/main/java/com/sparta/order/server/Cart/infrastructure/configuration/RedisConfig.java
Labels: ✨ Feature

#20 CI - build 구성
  .github/workflows/gradle-build.yml
Labels: ✅ Test

#61 CI 파이프 라인 수정
  .github/workflows/gradle-build.yml
Labels: 🛠Fix

#54 Auth 모듈에서 토큰 검증
  common/domain/src/main/java/com/sparta/common/domain/jwt/JwtGlobalConstant.java
  service/auth/dto/.gitignore
  service/auth/dto/build.gradle
  service/auth/dto/gradle/wrapper/gradle-wrapper.jar
  service/auth/dto/gradle/wrapper/gradle-wrapper.properties
  service/auth/dto/src/main/java/com/sparta/auth/dto/DtoApplication.java
  service/auth/dto/src/main/java/com/sparta/auth/dto/jwt/JwtClaim.java
  service/auth/server/build.gradle
  service/auth/server/src/main/java/com/sparta/auth/server/application/service/AuthService.java
  service/auth/server/src/main/java/com/sparta/auth/server/domain/JwtConstant.java
  service/auth/server/src/main/java/com/sparta/auth/server/exception/AuthErrorCode.java
  service/auth/server/src/main/java/com/sparta/auth/server/infrastructure/configuration/JwtConfig.java
  service/auth/server/src/main/java/com/sparta/auth/server/infrastructure/configuration/SecurityConfig.java
  service/auth/server/src/main/java/com/sparta/auth/server/infrastructure/utils/JwtHandler.java
  service/auth/server/src/main/java/com/sparta/auth/server/presentation/controller/AuthInternalController.java
  service/auth/server/src/test/java/com/sparta/auth/server/AuthApplicationTests.java
  service/auth/server/src/test/resources/application-test.yml
  service/gateway/server/src/test/java/com/sparta/gateway/server/GatewayApplicationTests.java
  settings.gradle
Labels: ✨ Feature, 🔧Refactor Require

#63 user, auth dto 수정
  service/auth/auth_dto/.gitignore
  service/auth/auth_dto/build.gradle
  service/auth/auth_dto/src/main/java/com/sparta/auth/auth_dto/AuthDtoApplication.java
  service/auth/auth_dto/src/main/java/com/sparta/auth/auth_dto/jwt/JwtClaim.java
  service/auth/dto/gradle/wrapper/gradle-wrapper.jar
  service/auth/dto/gradle/wrapper/gradle-wrapper.properties
  service/auth/server/build.gradle
  service/auth/server/src/main/java/com/sparta/auth/server/application/service/AuthService.java
  service/auth/server/src/main/java/com/sparta/auth/server/application/service/UserService.java
  service/auth/server/src/main/java/com/sparta/auth/server/infrastructure/feign/UserClient.java
  service/auth/server/src/main/java/com/sparta/auth/server/presentation/controller/AuthInternalController.java
  service/auth/server/src/test/java/com/sparta/auth/server/AuthApplicationTests.java
  service/user/dto/gradle/wrapper/gradle-wrapper.jar
  service/user/dto/gradle/wrapper/gradle-wrapper.properties
  service/user/server/build.gradle
  service/user/server/src/main/java/com/sparta/user/application/service/UserService.java
  service/user/server/src/main/java/com/sparta/user/presentation/controller/UserInternalController.java
  service/user/server/src/test/java/com/sparta/user/UserApplicationTests.java
  service/user/user_dto/.gitignore
  service/user/user_dto/build.gradle
  service/user/user_dto/src/main/java/com/sparta/user/user_dto/UserDtoApplication.java
  service/user/user_dto/src/main/java/com/sparta/user/user_dto/infrastructure/UserDto.java
  service/user/user_dto/src/main/java/com/sparta/user/user_dto/infrastructure/UserInternalDto.java
  settings.gradle
Labels: 🐞 Bug, 🛠Fix

#56 slack dto 모듈 생성
  service/slack/slack_dto/.gitignore
  service/slack/slack_dto/build.gradle
  service/slack/slack_dto/gradle/wrapper/gradle-wrapper.jar
  service/slack/slack_dto/gradle/wrapper/gradle-wrapper.properties
  service/slack/slack_dto/src/main/java/com/sparta/slack_dto/SlackDtoApplication.java
  service/slack/slack_dto/src/main/java/com/sparta/slack_dto/infrastructure/MessageInternalDto.java
  service/slack/slack_dto/src/main/resources/application.properties
  service/slack/slack_dto/src/test/java/com/sparta/slack_dto/SlackDtoApplicationTests.java
  settings.gradle
Labels: ✨ Feature

#57 결제 기본 API
  service/payment/server/build.gradle
  service/payment/server/src/main/java/com/sparta/payment/PaymentApplication.java
  service/payment/server/src/main/java/com/sparta/payment/application/dto/PaymentHistoryResponse.java
  service/payment/server/src/main/java/com/sparta/payment/application/dto/PaymentRequest.java
  service/payment/server/src/main/java/com/sparta/payment/application/dto/PaymentResponse.java
  service/payment/server/src/main/java/com/sparta/payment/application/service/PaymentService.java
  service/payment/server/src/main/java/com/sparta/payment/domain/entity/Payment.java
  service/payment/server/src/main/java/com/sparta/payment/domain/entity/PaymentHistory.java
  service/payment/server/src/main/java/com/sparta/payment/domain/entity/PaymentState.java
  service/payment/server/src/main/java/com/sparta/payment/domain/repository/PaymentHistoryRepository.java
  service/payment/server/src/main/java/com/sparta/payment/domain/repository/PaymentRepository.java
  service/payment/server/src/main/java/com/sparta/payment/exception/PaymentErrorCode.java
  service/payment/server/src/main/java/com/sparta/payment/exception/PaymentException.java
  service/payment/server/src/main/java/com/sparta/payment/exception/PaymentExceptionHandler.java
  service/payment/server/src/main/java/com/sparta/payment/presentation/PaymentController.java
  service/payment/server/src/main/resources/application-local.yml
Labels: ✨ Feature

#67 상품 조회 API 구현 및 상품 컬럼 추가
  service/product/product_dto/src/main/java/com/sparta/product_dto/ProductDto.java
  service/product/product_dto/src/main/java/com/sparta/product_dto/ProductReadRequest.java
  service/product/product_server/src/main/java/com/sparta/product/application/ProductMapper.java
  service/product/product_server/src/main/java/com/sparta/product/application/ProductService.java
  service/product/product_server/src/main/java/com/sparta/product/domain/model/Product.java
  service/product/product_server/src/main/java/com/sparta/product/infrastructure/elasticsearch/dto/ProductSearchDto.java
  service/product/product_server/src/main/java/com/sparta/product/presentation/controller/ProductController.java
  service/product/product_server/src/main/java/com/sparta/product/presentation/controller/ProductInternalController.java
  service/product/product_server/src/main/java/com/sparta/product/presentation/request/ProductCreateRequest.java
  service/product/product_server/src/main/java/com/sparta/product/presentation/request/ProductUpdateRequest.java
  service/product/product_server/src/main/java/com/sparta/product/presentation/response/ProductResponse.java
  service/product/product_server/src/test/java/com/sparta/product/ProductServerApplicationTests.java
Labels: ✨ Feature, 🔧Refactor Require

#70 payment dto 모듈 생성
  service/payment/payment_dto/.gitignore
  service/payment/payment_dto/build.gradle
  service/payment/payment_dto/src/main/java/com/sparta/payment_dto/PaymentDtoApplication.java
  service/payment/payment_dto/src/main/java/com/sparta/payment_dto/infrastructure/PaymentInternalDto.java
  service/payment/payment_dto/src/main/resources/application.properties
  service/payment/payment_dto/src/test/java/com/sparta/payment_dto/PaymentDtoApplicationTests.java
  settings.gradle
Labels: ✨ Feature

#79 장바구니 API 리팩토링
  service/order/server/build.gradle
  service/order/server/docs/CartApiTest.http
  service/order/server/src/main/java/com/sparta/order/server/Cart/application/service/CartService.java
  service/order/server/src/main/java/com/sparta/order/server/Cart/domain/model/CartProduct.java
  service/order/server/src/main/java/com/sparta/order/server/Cart/domain/model/ProductInfo.java
  service/order/server/src/main/java/com/sparta/order/server/Cart/infrastructure/client/ProductClient.java
  service/order/server/src/main/java/com/sparta/order/server/Cart/infrastructure/configuration/RedisConfig.java
  service/order/server/src/main/java/com/sparta/order/server/Cart/presentation/controller/CartController.java
  service/order/server/src/main/java/com/sparta/order/server/Cart/presentation/dto/CartDto.java
  service/order/server/src/main/java/com/sparta/order/server/OrderApplication.java
  service/product/product_server/src/main/java/com/sparta/product/application/ProductMapper.java
  service/product/product_server/src/main/java/com/sparta/product/presentation/controller/ProductInternalController.java
Labels: ✨ Feature, 🔨 Refactor

#58 상품 카테고리 CRUD 기능 구현
  common/domain/src/main/java/com/sparta/common/domain/response/ApiResponse.java
  docker-compose.yml
  service/product/product_server/build.gradle
  service/product/product_server/src/main/java/com/sparta/product/application/CategoryCache.java
  service/product/product_server/src/main/java/com/sparta/product/application/CategoryService.java
  service/product/product_server/src/main/java/com/sparta/product/domain/model/Category.java
  service/product/product_server/src/main/java/com/sparta/product/domain/repository/jpa/CategoryRepository.java
  service/product/product_server/src/main/java/com/sparta/product/infrastructure/configuration/RedisConfig.java
  service/product/product_server/src/main/java/com/sparta/product/infrastructure/configuration/RepositoryConfig.java
  service/product/product_server/src/main/java/com/sparta/product/presentation/controller/CategoryController.java
  service/product/product_server/src/main/java/com/sparta/product/presentation/controller/ProductController.java
  service/product/product_server/src/main/java/com/sparta/product/presentation/exception/ProductControllerAdvice.java
  service/product/product_server/src/main/java/com/sparta/product/presentation/exception/ProductErrorCode.java
  service/product/product_server/src/main/java/com/sparta/product/presentation/exception/ProductServerException.java
  service/product/product_server/src/main/java/com/sparta/product/presentation/request/CategoryCreateRequest.java
  service/product/product_server/src/main/java/com/sparta/product/presentation/request/CategoryUpdateRequest.java
  service/product/product_server/src/main/java/com/sparta/product/presentation/response/CategoryResponse.java
Labels: ✨ Feature

#73 등급 CRUD 기능 구현
  service/gateway/server/src/main/resources/application-local.yml
  service/user/server/src/main/java/com/sparta/user/application/dto/TierResponse.java
  service/user/server/src/main/java/com/sparta/user/application/service/TierService.java
  service/user/server/src/main/java/com/sparta/user/domain/model/Tier.java
  service/user/server/src/main/java/com/sparta/user/domain/repository/TierRepository.java
  service/user/server/src/main/java/com/sparta/user/exception/UserErrorCode.java
  service/user/server/src/main/java/com/sparta/user/infrastructure/repository/JpaTierRepository.java
  service/user/server/src/main/java/com/sparta/user/infrastructure/repository/TierRepositoryImpl.java
  service/user/server/src/main/java/com/sparta/user/presentation/controller/TierController.java
  service/user/server/src/main/java/com/sparta/user/presentation/request/TierRequest.java
  service/user/server/src/test/java/com/sparta/user/TierApplicationTests.java
  service/user/server/src/test/java/com/sparta/user/http/TierApiTest.http
  service/user/server/src/test/java/com/sparta/user/http/UserApiTest.http
Labels: ✨ Feature

#71 Payment internal controller 분리
  service/payment/server/src/main/java/com/sparta/payment/application/service/PaymentService.java
  service/payment/server/src/main/java/com/sparta/payment/domain/entity/Payment.java
  service/payment/server/src/main/java/com/sparta/payment/presentation/PaymentController.java
  service/payment/server/src/main/java/com/sparta/payment/presentation/PaymentInternalController.java
  service/payment/server/src/main/java/com/sparta/payment/presentation/dto/PaymentHistoryResponse.java
  service/payment/server/src/main/java/com/sparta/payment/presentation/dto/PaymentRequest.java
  service/payment/server/src/main/java/com/sparta/payment/presentation/dto/PaymentResponse.java
Labels: ✨ Feature

#80 포인트내역 추가 기능 구현
  service/user/server/src/main/java/com/sparta/user/application/service/PointHistoryService.java
  service/user/server/src/main/java/com/sparta/user/application/service/UserService.java
  service/user/server/src/main/java/com/sparta/user/domain/model/PointHistory.java
  service/user/server/src/main/java/com/sparta/user/domain/model/User.java
  service/user/server/src/main/java/com/sparta/user/domain/model/vo/PointHistoryType.java
  service/user/server/src/main/java/com/sparta/user/domain/repository/PointHistoryRepository.java
  service/user/server/src/main/java/com/sparta/user/domain/repository/UserRepository.java
  service/user/server/src/main/java/com/sparta/user/exception/UserErrorCode.java
  service/user/server/src/main/java/com/sparta/user/infrastructure/repository/JpaPointHistoryRepository.java
  service/user/server/src/main/java/com/sparta/user/infrastructure/repository/PointHistoryRepositoryImpl.java
  service/user/server/src/main/java/com/sparta/user/infrastructure/repository/UserRepositoryImpl.java
  service/user/server/src/main/java/com/sparta/user/presentation/controller/UserInternalController.java
  service/user/server/src/main/java/com/sparta/user/presentation/request/PointHistoryRequest.java
  service/user/server/src/main/java/com/sparta/user/presentation/request/UserRequest.java
  service/user/server/src/test/java/com/sparta/user/http/PointHistoryApiTest.http
  service/user/server/src/test/java/com/sparta/user/service/PointHistoryServiceTests.java
  service/user/server/src/test/java/com/sparta/user/service/UserServiceTests.java
  service/user/user_dto/src/main/java/com/sparta/user/user_dto/infrastructure/UserDto.java
  service/user/user_dto/src/main/java/com/sparta/user/user_dto/infrastructure/UserInternalDto.java
Labels: ✨ Feature

#83 배송지 생성, 배송지 단일 조회
  service/gateway/server/src/main/resources/application-local.yml
  service/user/server/src/main/java/com/sparta/user/application/service/AddressService.java
  service/user/server/src/main/java/com/sparta/user/domain/model/Address.java
  service/user/server/src/main/java/com/sparta/user/domain/model/User.java
  service/user/server/src/main/java/com/sparta/user/domain/repository/AddressRepository.java
  service/user/server/src/main/java/com/sparta/user/exception/UserErrorCode.java
  service/user/server/src/main/java/com/sparta/user/infrastructure/configuration/SecurityConfig.java
  service/user/server/src/main/java/com/sparta/user/infrastructure/repository/AddressRepositoryImpl.java
  service/user/server/src/main/java/com/sparta/user/infrastructure/repository/JpaAddressRepository.java
  service/user/server/src/main/java/com/sparta/user/presentation/controller/AddressController.java
  service/user/server/src/main/java/com/sparta/user/presentation/controller/AddressInternalController.java
  service/user/server/src/main/java/com/sparta/user/presentation/request/AddressRequest.java
  service/user/server/src/test/java/com/sparta/user/http/AddressApiTest.http
  service/user/server/src/test/java/com/sparta/user/service/AddressServiceTest.java
  service/user/user_dto/src/main/java/com/sparta/user/user_dto/infrastructure/AddressDto.java
Labels: ✨ Feature

#84 포인트 적립 및 사용 시 사용되는 Dto 수정
  service/user/server/src/main/java/com/sparta/user/application/service/PointHistoryService.java
  service/user/server/src/main/java/com/sparta/user/domain/model/PointHistory.java
  service/user/server/src/main/java/com/sparta/user/presentation/controller/UserInternalController.java
  service/user/server/src/main/java/com/sparta/user/presentation/request/PointHistoryRequest.java
  service/user/server/src/test/java/com/sparta/user/service/PointHistoryServiceTests.java
  service/user/user_dto/src/main/java/com/sparta/user/user_dto/infrastructure/PointHistoryDto.java
Labels: ✨ Feature

#82 상품목록 검색 API 구현
  docker-compose.yml
  service/product/product_server/.gitignore
  service/product/product_server/build.gradle
  service/product/product_server/src/main/java/com/sparta/product/application/ElasticSearchService.java
  service/product/product_server/src/main/java/com/sparta/product/application/ElasticsearchService.java
  service/product/product_server/src/main/java/com/sparta/product/application/ProductFacadeService.java
  service/product/product_server/src/main/java/com/sparta/product/domain/model/Product.java
  service/product/product_server/src/main/java/com/sparta/product/domain/model/SortOption.java
  service/product/product_server/src/main/java/com/sparta/product/domain/repository/ElasticsearchCustomRepository.java
  service/product/product_server/src/main/java/com/sparta/product/infrastructure/configuration/ElasticsearchClientConfig.java
  service/product/product_server/src/main/java/com/sparta/product/infrastructure/elasticsearch/dto/ProductSearchDto.java
  service/product/product_server/src/main/java/com/sparta/product/presentation/controller/CategoryController.java
  service/product/product_server/src/main/java/com/sparta/product/presentation/controller/ProductSearchController.java
  service/product/product_server/src/main/java/com/sparta/product/presentation/response/ProductResponse.java
  service/product/product_server/src/main/resources/application-local.yml
Labels: ✨ Feature, 🛠Fix, 🔧Refactor Require

#90 상품에 인증필터 적용
  service/product/server/.gitignore
  service/product/server/build.gradle
  service/product/server/src/main/java/com/sparta/product/ProductServerApplication.java
  service/product/server/src/main/java/com/sparta/product/application/CategoryCache.java
  service/product/server/src/main/java/com/sparta/product/application/CategoryService.java
  service/product/server/src/main/java/com/sparta/product/application/ElasticsearchService.java
  service/product/server/src/main/java/com/sparta/product/application/ProductFacadeService.java
  service/product/server/src/main/java/com/sparta/product/application/ProductMapper.java
  service/product/server/src/main/java/com/sparta/product/application/ProductService.java
  service/product/server/src/main/java/com/sparta/product/domain/model/Category.java
  service/product/server/src/main/java/com/sparta/product/domain/model/Product.java
  service/product/server/src/main/java/com/sparta/product/domain/model/SortOption.java
  service/product/server/src/main/java/com/sparta/product/domain/repository/ElasticSearchRepository.java
  service/product/server/src/main/java/com/sparta/product/domain/repository/ElasticsearchCustomRepository.java
  service/product/server/src/main/java/com/sparta/product/domain/repository/cassandra/ProductRepository.java
  service/product/server/src/main/java/com/sparta/product/domain/repository/jpa/CategoryRepository.java
  service/product/server/src/main/java/com/sparta/product/infrastructure/configuration/ElasticsearchClientConfig.java
  service/product/server/src/main/java/com/sparta/product/infrastructure/configuration/RedisConfig.java
  service/product/server/src/main/java/com/sparta/product/infrastructure/configuration/RepositoryConfig.java
  service/product/server/src/main/java/com/sparta/product/infrastructure/configuration/SecurityConfig.java
  service/product/server/src/main/java/com/sparta/product/infrastructure/elasticsearch/dto/ProductSearchDto.java
  service/product/server/src/main/java/com/sparta/product/infrastructure/filter/JwtAuthentication.java
  service/product/server/src/main/java/com/sparta/product/infrastructure/filter/SecurityContextFilter.java
  service/product/server/src/main/java/com/sparta/product/presentation/controller/CategoryController.java
  service/product/server/src/main/java/com/sparta/product/presentation/controller/ProductController.java
  service/product/server/src/main/java/com/sparta/product/presentation/controller/ProductInternalController.java
  service/product/server/src/main/java/com/sparta/product/presentation/controller/ProductSearchController.java
  service/product/server/src/main/java/com/sparta/product/presentation/exception/ProductControllerAdvice.java
  service/product/server/src/main/java/com/sparta/product/presentation/exception/ProductErrorCode.java
  service/product/server/src/main/java/com/sparta/product/presentation/exception/ProductServerException.java
  service/product/server/src/main/java/com/sparta/product/presentation/request/CategoryCreateRequest.java
  service/product/server/src/main/java/com/sparta/product/presentation/request/CategoryUpdateRequest.java
  service/product/server/src/main/java/com/sparta/product/presentation/request/ProductCreateRequest.java
  service/product/server/src/main/java/com/sparta/product/presentation/request/ProductUpdateRequest.java
  service/product/server/src/main/java/com/sparta/product/presentation/response/CategoryResponse.java
  service/product/server/src/main/java/com/sparta/product/presentation/response/ProductResponse.java
  service/product/server/src/main/resources/application-local.yml
  service/product/server/src/test/java/com/sparta/product/ProductServerApplicationTests.java
  settings.gradle
Labels: ✨ Feature

#87 이벤트 쿠폰 생성 및 발급 기능 구현
  service/gateway/server/src/main/resources/application-local.yml
  service/promotion/server/.gitignore
  service/promotion/server/build.gradle
  service/promotion/server/gradle/wrapper/gradle-wrapper.jar
  service/promotion/server/gradle/wrapper/gradle-wrapper.properties
  service/promotion/server/src/main/java/com/sparta/promotion/server/PromotionApplication.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/application/service/CouponService.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/domain/model/Coupon.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/domain/model/UserCoupon.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/domain/model/vo/CouponType.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/domain/model/vo/DiscountType.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/domain/repository/CouponRepository.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/domain/repository/UserCouponRepository.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/exception/PromotionControllerAdvice.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/exception/PromotionErrorCode.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/exception/PromotionException.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/infrastructure/configuration/SecurityConfig.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/infrastructure/filter/JwtAuthentication.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/infrastructure/filter/SecurityContextFilter.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/infrastructure/repository/CouponRepositoryImpl.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/infrastructure/repository/JpaCouponRepository.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/infrastructure/repository/JpaUserCouponRepository.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/infrastructure/repository/UserCouponRepositoryImpl.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/presentation/controller/CouponController.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/presentation/request/CouponRequest.java
  service/promotion/server/src/main/resources/application-local.yml
  service/promotion/server/src/main/resources/application.yml
  service/promotion/server/src/test/java/com/sparta/promotion/server/http/CouponApiTest.http
  service/promotion/server/src/test/java/com/sparta/promotion/server/service/CouponServiceTests.java
  settings.gradle
Labels: ✨ Feature, 🔧Refactor Require

#78 CI 파이브라인 수정
  .github/workflows/gradle-build.yml
Labels: 🛠Fix

#92 배송지 관련 기능 구현
  service/user/server/src/main/java/com/sparta/user/application/dto/AddressResponse.java
  service/user/server/src/main/java/com/sparta/user/application/service/AddressService.java
  service/user/server/src/main/java/com/sparta/user/domain/model/Address.java
  service/user/server/src/main/java/com/sparta/user/domain/model/vo/UserRole.java
  service/user/server/src/main/java/com/sparta/user/domain/repository/AddressRepository.java
  service/user/server/src/main/java/com/sparta/user/infrastructure/repository/AddressRepositoryImpl.java
  service/user/server/src/main/java/com/sparta/user/infrastructure/repository/JpaAddressRepository.java
  service/user/server/src/main/java/com/sparta/user/presentation/controller/AddressController.java
  service/user/server/src/main/java/com/sparta/user/presentation/request/AddressRequest.java
  service/user/server/src/test/java/com/sparta/user/http/AddressApiTest.http
  service/user/server/src/test/java/com/sparta/user/service/AddressServiceTest.java
  service/user/server/src/test/java/com/sparta/user/service/PointHistoryServiceTests.java
Labels: ✨ Feature, 🛠Fix

#93 상품 등록시 카테고리 검증 및 재고감소 내부 API 구현
  service/product/server/src/main/java/com/sparta/product/application/category/CategoryCache.java
  service/product/server/src/main/java/com/sparta/product/application/category/CategoryService.java
  service/product/server/src/main/java/com/sparta/product/application/product/ElasticsearchService.java
  service/product/server/src/main/java/com/sparta/product/application/product/ProductFacadeService.java
  service/product/server/src/main/java/com/sparta/product/application/product/ProductMapper.java
  service/product/server/src/main/java/com/sparta/product/application/product/ProductService.java
  service/product/server/src/main/java/com/sparta/product/domain/model/Product.java
  service/product/server/src/main/java/com/sparta/product/domain/repository/cassandra/ProductRepository.java
  service/product/server/src/main/java/com/sparta/product/domain/repository/jpa/CategoryRepository.java
  service/product/server/src/main/java/com/sparta/product/presentation/controller/CategoryController.java
  service/product/server/src/main/java/com/sparta/product/presentation/controller/ProductController.java
  service/product/server/src/main/java/com/sparta/product/presentation/controller/ProductInternalController.java
  service/product/server/src/main/java/com/sparta/product/presentation/controller/ProductSearchController.java
Labels: ✨ Feature, 🛠Fix

#94 결제 수정사항 반영
  service/payment/server/build.gradle
  service/payment/server/src/main/java/com/sparta/payment/application/service/ElasticSearchService.java
  service/payment/server/src/main/java/com/sparta/payment/application/service/PaymentService.java
  service/payment/server/src/main/java/com/sparta/payment/infrastructure/config/SecurityConfig.java
  service/payment/server/src/main/java/com/sparta/payment/infrastructure/event/PaymentCompletedEvent.java
  service/payment/server/src/main/java/com/sparta/payment/presentation/PaymentController.java
  service/payment/server/src/main/java/com/sparta/payment/presentation/dto/PaymentRequest.java
  service/payment/server/src/main/resources/application-local.yml
  service/payment/server/src/main/resources/templates/success.html
Labels: 🔨 Refactor

#98 사전예약 등록, 수정, 삭제, 조회 API 구현
  service/gateway/server/src/main/resources/application-local.yml
  service/product/server/src/main/java/com/sparta/product/application/preorder/PreOrderMapper.java
  service/product/server/src/main/java/com/sparta/product/application/preorder/PreOrderService.java
  service/product/server/src/main/java/com/sparta/product/domain/model/PreOrder.java
  service/product/server/src/main/java/com/sparta/product/domain/model/PreOrderState.java
  service/product/server/src/main/java/com/sparta/product/domain/model/Product.java
  service/product/server/src/main/java/com/sparta/product/domain/repository/jpa/PreOrderRepository.java
  service/product/server/src/main/java/com/sparta/product/presentation/controller/PreOrderController.java
  service/product/server/src/main/java/com/sparta/product/presentation/exception/ProductErrorCode.java
  service/product/server/src/main/java/com/sparta/product/presentation/request/PreOrderCreateRequest.java
  service/product/server/src/main/java/com/sparta/product/presentation/request/PreOrderUpdateRequest.java
  service/product/server/src/main/java/com/sparta/product/presentation/response/PreOrderResponse.java
Labels: ✨ Feature, 🔧Refactor Require

#105 elastic search 검색엔진
  service/search/server/.gitignore
  service/search/server/build.gradle
  service/search/server/gradle/wrapper/gradle-wrapper.jar
  service/search/server/gradle/wrapper/gradle-wrapper.properties
  service/search/server/src/main/java/com/sparta/server/SearchApplication.java
  service/search/server/src/main/java/com/sparta/server/application/SearchService.java
  service/search/server/src/main/java/com/sparta/server/domain/ProductSearchDto.java
  service/search/server/src/main/java/com/sparta/server/domain/SortOption.java
  service/search/server/src/main/java/com/sparta/server/exception/SearchErrorCode.java
  service/search/server/src/main/java/com/sparta/server/exception/SearchException.java
  service/search/server/src/main/java/com/sparta/server/exception/SearchExceptionHandler.java
  service/search/server/src/main/java/com/sparta/server/infrastructure/ElasticsearchClientConfig.java
  service/search/server/src/main/java/com/sparta/server/presentaion/SearchController.java
  service/search/server/src/main/resources/application-local.yml
  service/search/server/src/main/resources/application.properties
  service/search/server/src/test/java/com/sparta/server/SearchApplicationTests.java
  settings.gradle
Labels: ✨ Feature

#103 message 배포용 yml 생성
  service/slack/server/src/main/resources/application-prod.yml
  service/slack/server/src/main/resources/application.yml
Labels: ⚙️ Setting, 🌏 Deploy

#113 dev에 동시에 여러개가 merge 될 경우, 이전에 실행 중이던 dev 브랜치의 워크플로우가 취소
  .github/workflows/gradle-build.yml
Labels: ✨ Feature, 🌏 Deploy

#114 이벤트 CRUD
  service/gateway/server/src/main/resources/application.yml
  service/promotion/server/src/main/java/com/sparta/promotion/server/PromotionApplication.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/application/service/EventService.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/domain/model/Event.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/domain/repository/EventRepository.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/exception/PromotionErrorCode.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/infrastructure/configuration/SecurityConfig.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/presentation/controller/EventController.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/presentation/request/EventRequest.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/presentation/response/EventResponse.java
Labels: ✨ Feature

#116 결제 모듈 배포 진행
  .github/workflows/gradle-build.yml
  docker-compose.yml
  dockerTagAndPush.sh
  service/payment/server/src/main/resources/application-prod.yml
Labels: 🌏 Deploy

#117 슬랙 모듈 배포
  .github/workflows/gradle-build.yml
  docker-compose.yml
  dockerTagAndPush.sh
  service/slack/server/src/main/resources/application-prod.yml
Labels: 🌏 Deploy

#122 주문 API와 결제 API 연결
  service/order/server/build.gradle
  service/order/server/docs/OrderApiTest.http
  service/order/server/src/main/java/com/sparta/order/server/application/service/OrderCreateService.java
  service/order/server/src/main/java/com/sparta/order/server/application/service/OrderService.java
  service/order/server/src/main/java/com/sparta/order/server/domain/model/Order.java
  service/order/server/src/main/java/com/sparta/order/server/infrastructure/client/PaymentClient.java
  service/order/server/src/main/java/com/sparta/order/server/presentation/dto/OrderDto.java
  service/payment/payment_dto/src/main/java/com/sparta/payment_dto/infrastructure/PaymentInternalDto.java
  service/payment/payment_dto/src/main/resources/application.properties
  service/payment/server/src/main/java/com/sparta/payment/application/service/PaymentService.java
  service/payment/server/src/main/java/com/sparta/payment/presentation/PaymentInternalController.java
Labels: ✨ Feature

#125 search 모듈 배포
  .github/workflows/gradle-build.yml
  docker-compose.yml
  dockerTagAndPush.sh
  service/search/server/src/main/resources/application-local.yml
  service/search/server/src/main/resources/application-prod.yml
  service/search/server/src/main/resources/application.properties
  service/search/server/src/main/resources/application.yml
Labels: 🌏 Deploy

#124 ec2 환경에서 서비스 실행 시 DB 비밀번호
  .github/workflows/gradle-build.yml
  docker-compose.yml
  service/order/server/src/main/resources/application-prod.yml
  service/order/server/src/main/resources/application.yml
Labels: 🌏 Deploy, 🐞 Bug

#126 주문 상세조회 API
  service/order/server/docs/OrderApiTest.http
  service/order/server/src/main/java/com/sparta/order/server/application/service/OrderCreateService.java
  service/order/server/src/main/java/com/sparta/order/server/application/service/OrderService.java
  service/order/server/src/main/java/com/sparta/order/server/domain/model/Order.java
  service/order/server/src/main/java/com/sparta/order/server/domain/model/OrderProduct.java
  service/order/server/src/main/java/com/sparta/order/server/exception/OrderErrorCode.java
  service/order/server/src/main/java/com/sparta/order/server/infrastructure/client/PaymentClient.java
  service/order/server/src/main/java/com/sparta/order/server/presentation/controller/OrderController.java
  service/order/server/src/main/java/com/sparta/order/server/presentation/dto/OrderDto.java
  service/payment/payment_dto/src/main/java/com/sparta/payment_dto/infrastructure/PaymentInternalDto.java
Labels: ✨ Feature

#130 search query 수정, 상품 검색/조회 403 에러 수정
  service/gateway/server/src/main/java/com/sparta/gateway/server/infrastructure/filter/JwtAuthenticationFilter.java
  service/payment/server/src/main/java/com/sparta/payment/infrastructure/config/SecurityConfig.java
  service/product/server/src/main/java/com/sparta/product/presentation/controller/PreOrderController.java
  service/product/server/src/main/java/com/sparta/product/presentation/controller/ProductController.java
  service/search/server/src/main/java/com/sparta/server/application/SearchService.java
Labels: 🛠Fix

#135 사전예약 로직 수정
  service/product/server/src/main/java/com/sparta/product/application/preorder/PreOrderCacheService.java
  service/product/server/src/main/java/com/sparta/product/application/preorder/PreOrderFacadeService.java
  service/product/server/src/main/java/com/sparta/product/application/preorder/PreOrderLockService.java
  service/product/server/src/main/java/com/sparta/product/application/preorder/PreOrderService.java
  service/product/server/src/main/java/com/sparta/product/infrastructure/utils/PreOrderRedisDto.java
Labels: ✨ Feature, 🛠Fix

#137 상품서버 API 인가처리 및 AuditorAware 기능 추가
  service/gateway/server/src/main/java/com/sparta/gateway/server/infrastructure/filter/JwtAuthenticationFilter.java
  service/product/server/src/main/java/com/sparta/product/infrastructure/configuration/AuditAwareImpl.java
  service/product/server/src/main/java/com/sparta/product/infrastructure/configuration/RepositoryConfig.java
  service/product/server/src/main/java/com/sparta/product/infrastructure/configuration/SecurityConfig.java
  service/product/server/src/main/java/com/sparta/product/presentation/controller/CategoryController.java
  service/product/server/src/main/java/com/sparta/product/presentation/controller/PreOrderController.java
  service/product/server/src/main/java/com/sparta/product/presentation/controller/ProductController.java
  service/product/server/src/main/java/com/sparta/product/presentation/controller/ProductSearchController.java
  service/product/server/src/main/java/com/sparta/product/presentation/exception/ProductControllerAdvice.java
  service/product/server/src/main/java/com/sparta/product/presentation/exception/ProductErrorCode.java
Labels: ✨ Feature

#138 쿠폰 관련 기능 구현
  service/promotion/server/src/main/java/com/sparta/promotion/server/application/service/CouponService.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/domain/model/Coupon.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/domain/model/UserCoupon.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/domain/repository/CouponRepository.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/domain/repository/UserCouponRepository.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/exception/PromotionErrorCode.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/infrastructure/configuration/SecurityConfig.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/infrastructure/repository/CouponRepositoryImpl.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/infrastructure/repository/JpaUserCouponRepository.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/infrastructure/repository/UserCouponRepositoryImpl.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/presentation/controller/CouponController.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/presentation/controller/CouponInternalController.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/presentation/request/CouponRequest.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/presentation/response/CouponResponse.java
  service/promotion/server/src/test/java/com/sparta/promotion/server/http/CouponApiTest.http
  service/promotion/server/src/test/java/com/sparta/promotion/server/service/CouponServiceTests.java
  service/promotion/server/src/test/resources/application.yml
Labels: ✨ Feature

#139 사용자 관련 기능 추가
  service/user/server/src/main/java/com/sparta/user/UserApplication.java
  service/user/server/src/main/java/com/sparta/user/application/dto/UserResponse.java
  service/user/server/src/main/java/com/sparta/user/application/service/UserService.java
  service/user/server/src/main/java/com/sparta/user/domain/model/User.java
  service/user/server/src/main/java/com/sparta/user/domain/repository/UserRepository.java
  service/user/server/src/main/java/com/sparta/user/exception/UserControllerAdvice.java
  service/user/server/src/main/java/com/sparta/user/exception/UserErrorCode.java
  service/user/server/src/main/java/com/sparta/user/exception/UserException.java
  service/user/server/src/main/java/com/sparta/user/infrastructure/repository/JpaUserRepository.java
  service/user/server/src/main/java/com/sparta/user/infrastructure/repository/UserRepositoryImpl.java
  service/user/server/src/main/java/com/sparta/user/presentation/controller/UserController.java
  service/user/server/src/main/java/com/sparta/user/presentation/request/UserRequest.java
  service/user/server/src/test/java/com/sparta/user/http/UserApiTest.http
  service/user/server/src/test/java/com/sparta/user/service/AddressServiceTest.java
  service/user/server/src/test/java/com/sparta/user/service/PointHistoryServiceTests.java
  service/user/server/src/test/java/com/sparta/user/service/TierServiceTests.java
  service/user/server/src/test/java/com/sparta/user/service/UserServiceTests.java
Labels: ✨ Feature

#141 사용자 등급 관련 기능
  service/user/server/src/main/java/com/sparta/user/application/dto/UserTierResponse.java
  service/user/server/src/main/java/com/sparta/user/application/service/UserService.java
  service/user/server/src/main/java/com/sparta/user/domain/model/User.java
  service/user/server/src/main/java/com/sparta/user/domain/model/UserTier.java
  service/user/server/src/main/java/com/sparta/user/domain/repository/UserTierRepository.java
  service/user/server/src/main/java/com/sparta/user/exception/UserErrorCode.java
  service/user/server/src/main/java/com/sparta/user/infrastructure/repository/JpaUserTierRepository.java
  service/user/server/src/main/java/com/sparta/user/infrastructure/repository/UserTierRepositoryImpl.java
  service/user/server/src/main/java/com/sparta/user/presentation/controller/UserTierController.java
  service/user/server/src/main/java/com/sparta/user/presentation/request/UserRequest.java
  service/user/server/src/test/java/com/sparta/user/http/UserApiTest.http
  service/user/server/src/test/java/com/sparta/user/service/UserServiceTests.java
Labels: ✨ Feature

#142 주문 관련 API 마무리
  service/order/server/docs/OrderApiTest.http
  service/order/server/src/main/java/com/sparta/order/server/application/service/OrderCreateService.java
  service/order/server/src/main/java/com/sparta/order/server/application/service/OrderService.java
  service/order/server/src/main/java/com/sparta/order/server/domain/model/Order.java
  service/order/server/src/main/java/com/sparta/order/server/domain/repository/OrderRepositoryCustom.java
  service/order/server/src/main/java/com/sparta/order/server/domain/repository/OrderRepositoryImpl.java
  service/order/server/src/main/java/com/sparta/order/server/exception/OrderErrorCode.java
  service/order/server/src/main/java/com/sparta/order/server/presentation/controller/OrderController.java
  service/order/server/src/main/java/com/sparta/order/server/presentation/dto/OrderDto.java
Labels: ✨ Feature

#143 포인트 내역 기능 구현
  service/user/server/src/main/java/com/sparta/user/application/dto/PointResponse.java
  service/user/server/src/main/java/com/sparta/user/application/service/PointHistoryService.java
  service/user/server/src/main/java/com/sparta/user/domain/repository/PointHistoryRepository.java
  service/user/server/src/main/java/com/sparta/user/exception/UserErrorCode.java
  service/user/server/src/main/java/com/sparta/user/infrastructure/repository/JpaPointHistoryRepository.java
  service/user/server/src/main/java/com/sparta/user/infrastructure/repository/PointHistoryRepositoryImpl.java
  service/user/server/src/main/java/com/sparta/user/presentation/controller/PointHistoryController.java
  service/user/server/src/main/java/com/sparta/user/presentation/controller/UserController.java
  service/user/server/src/test/java/com/sparta/user/http/PointHistoryApiTest.http
  service/user/server/src/test/java/com/sparta/user/service/PointHistoryServiceTests.java
Labels: ✨ Feature

#147 주문 시 재고 감소, 재고 롤백 동시성 처리
  service/order/server/docs/OrderApiTest.http
  service/product/server/src/main/java/com/sparta/product/application/preorder/DistributedLockComponent.java
  service/product/server/src/main/java/com/sparta/product/application/product/ProductLockService.java
  service/product/server/src/main/java/com/sparta/product/application/product/ProductService.java
  service/product/server/src/main/java/com/sparta/product/presentation/controller/ProductInternalController.java
  service/product/server/src/main/java/com/sparta/product/presentation/exception/ProductErrorCode.java
Labels: ✨ Feature

#150 외부 저장소에 상품이미지 업로드 기능 구현
  service/product/server/build.gradle
  service/product/server/src/main/java/com/sparta/product/application/dto/ImgDto.java
  service/product/server/src/main/java/com/sparta/product/application/product/ImageService.java
  service/product/server/src/main/java/com/sparta/product/application/product/ProductFacadeService.java
  service/product/server/src/main/java/com/sparta/product/application/product/ProductMapper.java
  service/product/server/src/main/java/com/sparta/product/application/product/ProductService.java
  service/product/server/src/main/java/com/sparta/product/application/product/S3ImageService.java
  service/product/server/src/main/java/com/sparta/product/domain/model/Product.java
  service/product/server/src/main/java/com/sparta/product/infrastructure/configuration/S3Config.java
  service/product/server/src/main/java/com/sparta/product/presentation/controller/ProductController.java
  service/product/server/src/main/java/com/sparta/product/presentation/request/ProductCreateRequest.java
  service/product/server/src/main/java/com/sparta/product/presentation/request/ProductUpdateRequest.java
  service/product/server/src/main/java/com/sparta/product/presentation/response/ProductResponse.java
  service/product/server/src/main/resources/application-local.yml
  service/product/server/src/main/resources/application-prod.yml
Labels: ⚙️ Setting, ✨ Feature

#153 쿠폰 발행 기능 고도화
  common/domain/src/main/java/com/sparta/common/domain/entity/KafkaTopicConstant.java
  docker-compose-dep.yml
  service/promotion/server/build.gradle
  service/promotion/server/src/main/java/com/sparta/promotion/server/PromotionApplication.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/application/service/CouponService.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/application/service/DistributedLockComponent.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/application/service/UserService.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/infrastructure/configuration/RedissonConfig.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/infrastructure/configuration/UserFeignConfig.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/infrastructure/feign/UserClient.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/infrastructure/feign/UserErrorDecoder.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/infrastructure/messaging/CouponEventConsumer.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/presentation/controller/CouponController.java
  service/promotion/server/src/main/java/com/sparta/promotion/server/presentation/request/CouponRequest.java
  service/promotion/server/src/main/resources/application-local.yml
  service/promotion/server/src/main/resources/application-prod.yml
  service/promotion/server/src/test/java/com/sparta/promotion/server/http/CouponApiTest.http
  service/promotion/server/src/test/java/com/sparta/promotion/server/service/CouponServiceTests.java
  service/promotion/server/src/test/resources/application-test.yml
Labels: ✨ Feature

#152 fix(#91): S3 저장시 썸네일 이미지 경로도 함께 만들어서 저장
  service/product/server/src/main/java/com/sparta/product/application/dto/ImgDto.java
  service/product/server/src/main/java/com/sparta/product/application/product/ProductFacadeService.java
  service/product/server/src/main/java/com/sparta/product/application/product/ProductMapper.java
  service/product/server/src/main/java/com/sparta/product/application/product/ProductService.java
  service/product/server/src/main/java/com/sparta/product/domain/model/Product.java
Labels: 🛠Fix, 🔧Refactor Require

#157 사전 예약 주문 생성 오류 해결
  service/order/server/src/main/java/com/sparta/order/server/application/service/OrderCreateService.java
  service/order/server/src/main/java/com/sparta/order/server/domain/model/Order.java
  service/product/server/src/main/java/com/sparta/product/application/preorder/PreOrderMapper.java
Labels: 🐞 Bug, 🛠Fix

#158 Gateway 대기열 도입
  docker-compose-dep.yml
  service/gateway/server/build.gradle
  service/gateway/server/src/main/java/com/sparta/gateway/server/GatewayApplication.java
  service/gateway/server/src/main/java/com/sparta/gateway/server/application/DistributedLockComponent.java
  service/gateway/server/src/main/java/com/sparta/gateway/server/application/UserQueueService.java
  service/gateway/server/src/main/java/com/sparta/gateway/server/application/dto/RegisterUserResponse.java
  service/gateway/server/src/main/java/com/sparta/gateway/server/infrastructure/configuration/RedissonConfig.java
  service/gateway/server/src/main/java/com/sparta/gateway/server/infrastructure/exception/GatewayErrorCode.java
  service/gateway/server/src/main/java/com/sparta/gateway/server/infrastructure/exception/GatewayException.java
  service/gateway/server/src/main/java/com/sparta/gateway/server/infrastructure/exception/GatewayExceptionHandler.java
  service/gateway/server/src/main/java/com/sparta/gateway/server/infrastructure/filter/GlobalQueueFilter.java
  service/gateway/server/src/main/java/com/sparta/gateway/server/infrastructure/filter/JwtAuthenticationFilter.java
  service/gateway/server/src/main/resources/application-local.yml
  service/gateway/server/src/main/resources/application-prod.yml
  service/gateway/server/src/main/resources/application.yml
  service/promotion/server/src/main/java/com/sparta/promotion/server/presentation/controller/CouponController.java
Labels: ✨ Feature
